config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
    
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
   
  get 'signup', to: 'users#new'
  
 
  resources :tasks
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
     validates :content, presence: true, length: { maximum: 255 }
     validates :status, presence: true, length: { maximum: 10 }
     
     belongs_to :user
     
     
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
     has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
     private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_user_logged_in
    before_action :correct_user, only: [:destroy, :show, :update, :edit ]

    def index
         @tasks = current_user.tasks.order(id: :desc).page(params[:page])
    end
    
   
    
    def new
        @task = Task.new
    end
    
    def create
        @task = current_user.tasks.build(task_params)
        
        if @task.save
           flash[:success] = 'Task が正常に投稿されました'
           redirect_to @task
        else @tasks = current_user.tasks.order(id: :desc).page(params[:page])
            flash[:danger] = 'Task が投稿されませんでした'
            render :new
        end
    end
    
    
    
    def update
        
        
        if @task.update(task_params)
            flash[:success] = 'Task　は正常に更新されました'
            redirect_to @task
        else
            flash.now[:danger] ='Task は更新されませんでした'
            render :edit
        end
    end
    
    def destroy
        
        @task.destroy
        
        flash[:success] = 'Task は正常に削除されました'
        redirect_to tasks_url
    end

private

  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  
  def correct_user
      @task = current_user.tasks.find_by(id: params[:id])
      unless @task
          redirect_to root_url
      end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  
 
  def new
     @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url 
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
      
    end
  end
  
   private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">タスク管理アプリ</a>
    <!-- 横幅が狭い時に出るハンバーガーボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- メニュー項目 -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            
            <ul class="dropdown-menu dropdown-menu-right">
              
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
          
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
<div class="col-6">
<%= form_with(model: task, local: true) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <ul class="mb-0">
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :status, 'status' %>
    <%= f.text_field :status, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content, 'タスク' %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>

  <%= f.submit '投稿', class: 'btn btn-primary' %>
<% end %>
</div>
</div>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> 編集ページ </h1> 

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<% if @tasks.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>タイトル</th>
        <th>メッセージ</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.id, task %></td>
          <td><%= task.status %></td>
          <td><%= task.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @tasks %>
  </div>
<% end %>
<%= link_to '新規タスクの投稿', new_task_path, class: "btn btn-primary" %>

app/views/tasks/new.html.erb
<h1>作成ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> 詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>タイトル</th>
    <td><%= @task.status %></td>
  </tr>
  <tr>
    <th>メッセージ</th>
    <td><%= @task.content %></td>
  </tr>
</table>

<%= link_to '編集ページ', edit_task_path(@task), class: 'btn btn-light' %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>